/**
 * pokeseen - <https://github.com/msikma/pokeseen>
 * Copyright © 2018, Michiel Sikma
 */

import fs from 'fs'
import path from 'path'
import React from 'react'
import ReactDOMServer from 'react-dom/server'
import getRepoInfo from 'repoinfojs'
import moment from 'moment'
import { get, xor } from 'lodash'
import classnames from 'classnames'

import { pkgData, epURL, pokedex } from './data'
import { saveFile } from './util/saveFile'

const modulesPath = path.resolve(__dirname, '..', 'node_modules')
const docsPath = path.resolve(__dirname, '..', 'docs')
const staticPath = path.resolve(__dirname, '..', 'static')

const never = 'Never seen'

/**
 * Generates and saves an HTML page containing the appearance data
 * generated by sortPokemonByAppearances().
 */
export const createSeenPage = async (appearancesRanking, appearanceDataSpecials, lastSeenRanking, airedEpisodesList, specialEpisodesList) => {
  // Generate some data from the repo.
  const repoInfo = await getRepoInfo()
  const data = {
    version: pkgData.version,
    commits: repoInfo.commits,
    hash: repoInfo.hash,
    homepage: pkgData.homepage,
    generationTime: moment().format('YYYY-MM-DD HH:mm:ssZZ')
  }
  // Render our React component to HTML and save it using the wrapper string.
  const lastSeenRankingByID = lastSeenRanking
    .map((item, n) => ({ ...item, n }))
    .reduce((acc, item) => ({ ...acc, [item.id]: item }), {})
  const pageMarkup = ReactDOMServer.renderToStaticMarkup(<SeenPage { ...{ lastSeenRankingByID, appearanceDataSpecials, appearancesRanking, airedEpisodesList, specialEpisodesList, ...data } } />)
  await saveFile(`${docsPath}/index.html`, wrapPage(pageMarkup, data))

  // Copy over some necessary files.
  await copyFile(`${modulesPath}/pokesprite/overview.min.css`, docsPath)
  await copyFile(`${staticPath}/pokeseen.css`, docsPath)
  await copyFile(`${staticPath}/pokeseen.js`, docsPath)

  console.log(`Saved PokéSeen page to ${docsPath}/index.html and copied over static resources.`)
}

/**
 * Copies a file from a path to a destination directory.
 */
const copyFile = (src, destDir) => new Promise((resolve, reject) => {
  const dest = `${destDir}/${path.basename(src)}`
  fs.copyFile(src, dest, (err) => {
    if (err) return reject(err)
    return resolve()
  })
})

/**
 * Pokémon icon component.
 */
const PokemonIcon = ({ pkmnInfo, id }) => {
  const slug = pkmnInfo.slug.eng
  return (
    <span id={ `icon_${id}` } className={ `pkspr pkmn-${slug}` }>
      <img src={ `https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/${slug}.png` } />
    </span>
  )
}

/**
 * Returns the episode series identifier, and whether this is a special.
 */
const getEpisodeSeries = (ep) => {
  if (ep == null) {
    return 'none'
  }
  let isSpecial = false
  let series = ep.toLowerCase().replace(/[0-9]*/g, '')
  let number = Number(ep.toLowerCase().replace(/[a-z]*/g, ''))
  if (series[2] === 's') {
    series = series.slice(0, 2)
    isSpecial = true
  }
  if (series === 'ep' && number >= 117) {
    series = 'gs'
  }
  return {series, isSpecial, number}
}

/**
 * Returns the Pokémon's origin region.
 */
const getPokemonOrigin = (pkmnInfo) => {
  const id = Number(pkmnInfo.idx)
  let value = 'Kanto'
  if (id >= 152) value = 'Johto'
  if (id >= 252) value = 'Hoenn'
  if (id >= 387) value = 'Sinnoh'
  if (id >= 494) value = 'Unova' // Issyu
  if (id >= 650) value = 'Kalos'
  if (id >= 722) value = 'Alola'
  if (id >= 810) value = 'Galar'
  if (id >= 906) value = 'Paldea'
  return {slug: value.toLowerCase(), title: value}
}

/**
 * Episode link component.
 */
const EpisodeLink = ({ ep }) => {
  const {series, isSpecial} = getEpisodeSeries(ep)
  return (
    <li><a className={ classnames('t', `ep-series-${series}`, { special: isSpecial }) } target="_blank" href={ epURL(ep) }>{ ep }</a></li>
  )
}

/**
 * Main component.
 *
 * The Pokémon ranking data uses the following format:
 *
 * [ { id: '789',
 *     amount: 9,
 *     lastSeen: { ja: '2018-05-10', us: '2018-04-07' } }, ... ]
 */
const SeenPage = ({ lastSeenRankingByID, appearanceDataSpecials, appearancesRanking, airedEpisodesList, specialEpisodesList, version, commits, hash, homepage, generationTime }) => (
  <div id="top">
    <div className="description">
      <div className="header">
        <h1>Pokémon TV appearance statistics</h1>
        <p>This page ranks Pokémon based on how many times they've appeared in the TV show and lists when we last saw them.</p>
        <p>このページは、ポケモンがアニメに何度登場したか、いつ最後に登場したかを確認できます。</p>
      </div>
      <div className="docs-container">
        <p>
          <em>Appearances</em> lists the number of episodes the Pokémon has appeared in.
          Its <em>last appearance</em> is based on the Japanese episode schedule.
          Click on a Pokémon's table row to see the list of episodes it has appeared in.
          The ranking uses statistics from the currently released { airedEpisodesList.length } episodes (and { specialEpisodesList.length } specials).
        </p>
        <p className="bottom-line">For questions or comments you can <a href="https://twitter.com/dada78641" title="@dada78641">contact me on Twitter.</a></p>
        <p>
          「登場数」はポケモンがアニメに何度登場したか示してあります。また、「最後の登場」はポケモンが最後に登場したエピソードの日程を示してあります。
          テーブルの行をクリックするとそのポケモンが登場したエピソードのリストを見ることができます。
          このランキングは現在{ airedEpisodesList.length }エピソードのデータを基にしてます。
        </p>
        <p className="bottom-line">質問やコメントがあれば、<a href="https://twitter.com/dada78641" title="@dada78641">ツイッターで連絡してください。</a></p>
        <p id="generation_time">Generated <span className="time-abs-prefix">on</span><span className="time" data-time={ +new Date(generationTime) } title={ generationTime }>{ generationTime }</span>.</p>
        <script dangerouslySetInnerHTML={{__html: `PokeSeen.humanizeGenerationTime()` }}></script>
      </div>
    </div>
    <table className="table pkspr-overview" id="data_table">
      <tbody>
        <tr>
          <th>#</th>
          <th>ID</th>
          <th className="center">Icon</th>
          <th colSpan={ 2 }>Name</th>
          <th><a href="#" className="sort-link active" id="appearance_sort"><span className="regular-label">Appearances</span><span className="small-label">Eps</span></a></th>
          <th className="center"><span className="regular-label">Origin</span></th>
          <th colSpan={ 3 } className="last-episode-col"><a href="#" className="sort-link" id="last_seen_sort"><span className="regular-label">Last appearance</span><span className="small-label">Last seen/最後の登場</span></a></th>
        </tr>
        <script dangerouslySetInnerHTML={{__html: `PokeSeen.decorateSorters('appearance_sort', 'last_seen_sort')` }}></script>
        { appearancesRanking.map((pokemon, n) => {
          // Construct two rows: one with the sorted data, and one with the episode IDs.
          const { amount, amountIncSpecials, lastSeen, episodes } = pokemon
          const id = String(Number(pokemon.id)).padStart(3, '0')
          const idNumber = Number(id)

          // Check if it's faster to see which episodes a Pokémon did *not* appear in.
          const episodesInverse = xor(airedEpisodesList, episodes)
          // If this Pokémon is in more episodes than half.
          const hasReallyManyEpisodes = episodes.length > episodesInverse.length

          const pkmnInfo = pokedex[id]
          const bulbaLink = `https://bulbapedia.bulbagarden.net/wiki/${pkmnInfo.name.eng}_(Pokémon)`

          const cols = 10
          const isLast = n === appearancesRanking.length - 1

          // If listing fewer than this amount of episodes, switch to a different layout.
          const fewEpisodes = 12

          // Sort order. All * 2, since we've actually got two rows per item.
          const orderAppearances = n * 2
          const orderLastSeen = lastSeenRankingByID[id].n * 2

          // Whether to use 'appears in all episodes *except*' type lists if they are shorter.
          const useExceptLists = false

          // Determine specials this Pokémon was seen in.
          const pokemonSpecialData = appearanceDataSpecials[id]
          const specials = pokemonSpecialData.episodes.length === 0 ? null : (
            <div className={ classnames('ep-cols specials', { short: episodes.length < fewEpisodes }) }>
              <div className="ep-header">Specials:</div>
              <ul className="ep-content">{ pokemonSpecialData.episodes.map(ep => (<EpisodeLink ep={ ep } key={ ep } />)) }</ul>
            </div>
          )

          // The last episode it appeared in.
          const lastEpisode = episodes[episodes.length - 1]
          const lastSpecial = pokemonSpecialData.episodes[pokemonSpecialData.episodes.length - 1]

          // Determine the last time this Pokémon was seen, if ever.
          // The relative time is later humanized dynamically.
          const lastJaRegular = get(lastSeen, 'ja', null)
          const lastJaSpecial = get(pokemonSpecialData.lastSeen, 'ja', null)
          const neverSeenJa = (!lastJaRegular) && (!lastJaSpecial)

          // The lastSeen variables are YYYY-MM-DD dates, so we can compare them normally.
          const lastIsSpecial = lastJaSpecial == null
            ? false
            : lastJaRegular == null
              ? true
              : (lastJaRegular >= lastJaSpecial)
                ? false
                : true
          const lastJa = lastIsSpecial ? lastJaSpecial : lastJaRegular
          const lastJaInt = moment().diff(moment(lastJa), 'ms')
          const lastEpisodeSeries = getEpisodeSeries(lastEpisode)
          const pokemonOrigin = getPokemonOrigin(pkmnInfo)

          return [
            <tr
              key={ `main_info_${id}` }
              id={ `item_${id}` }
              className={ classnames('main-info', { 'last': isLast }) }
              data-id={ id }
              data-last-seen-n={ orderLastSeen }
              data-appearances-n={ orderAppearances }
            >
              <td className="minimal id">{ n + 1 }</td>
              <td className="minimal">{ id }</td>
              <td className="minimal"><PokemonIcon pkmnInfo={ pkmnInfo } id={ id } /></td>
              <td className="name name-en">{ pkmnInfo.name.eng }</td>
              <td className="name name-jp"><span title={ pkmnInfo.name.jpn_ro }>{ pkmnInfo.name.jpn }</span></td>
              <td>{ amountIncSpecials }</td>
              <td className={ classnames('minimal') }><span className={ classnames('t', `origin-${pokemonOrigin.slug}`) }>{ pokemonOrigin.title }</span></td>
              <td className={ neverSeenJa ? 'never' : `last-episode series series-${lastEpisodeSeries.series}` } { ...(neverSeenJa ? { colSpan: 3 } : {}) }><span className="t">{ neverSeenJa ? never : (lastIsSpecial ? lastSpecial : lastEpisode) }</span></td>
              { !neverSeenJa ? <td className="last-ja">{ lastJa }</td> : null }
              { !neverSeenJa ? <td className="time-ago" data-time-ago-ms={ isNaN(lastJaInt) ? -1 : lastJaInt }></td> : null }
            </tr>,
            <tr
              id={ `episodes_${id}` }
              className={ classnames('episode-info', { last: isLast }) }
              data-id={ id }
              data-last-seen-n={ orderLastSeen + 1 }
              data-appearances-n={ orderAppearances + 1 }
              key={ `ep_info_${id}` }
            >
              { episodesInverse.length === 0
                ? <td colSpan={ cols } className="ep-cols-container">Appears in every episode to date.{ specials }</td>
                : episodes.length === 0
                  ? <td colSpan={ cols } className="ep-cols-container">No appearances in the TV series.{ specials }</td>
                  : episodesInverse.length > episodes.length || !useExceptLists
                    ? (
                      <td colSpan={ cols } className="ep-cols-container">
                        <div className={ classnames('ep-cols', 'general') }>
                          <div className="ep-header">General info:</div>
                          <div className="general-content">
                            <ul>
                              <li><a href={ bulbaLink }>{ pkmnInfo.name.eng } article on Bulbapedia</a></li>
                            </ul>
                          </div>
                        </div>
                        <div className={ classnames('ep-cols', { short: episodes.length < fewEpisodes }) }>
                          <div className="ep-header">Appears in:</div>
                          <div className="ep-content-group">
                            { hasReallyManyEpisodes ? [
                              <div key="a" className="ep-content-header">Appears in all episodes <em>except</em>:</div>,
                              <ul key="b" className="ep-content">{ episodesInverse.map(ep => (<EpisodeLink ep={ ep } key={ ep } />)) }</ul>,
                              <div key="c" className="ep-content-header">Episodes it appears in:</div>
                            ] : null }
                            <ul className="ep-content">{ episodes.map(ep => (<EpisodeLink ep={ ep } key={ ep } />)) }</ul>
                          </div>
                        </div>
                        { specials }
                      </td>
                    )
                    : (
                      <td colSpan={ cols } className="ep-cols-container">
                        <div className={ classnames('ep-cols', { short: episodesInverse.length < fewEpisodes }) }>
                          <div className="ep-header">Appears in every episode <em>except</em>:</div>
                          <ul className="ep-content">{ episodesInverse.map(ep => (<EpisodeLink ep={ ep } key={ ep } />)) }</ul>
                        </div>
                        { specials }
                      </td>
                    ) }
            </tr>,
            <script key={ `js_${id}` } dangerouslySetInnerHTML={{__html: `PokeSeen.decorate('${id}')` }}></script>
          ]
        })}
      </tbody>
    </table>
    <div className="description">
      <div className="docs-container closing">
        <p>Pokémon is © 1995-{ (new Date().getFullYear()) } Nintendo/Creatures Inc./GAME FREAK Inc.</p>
        <p>The source code for this page is available on <a href="https://github.com/msikma/pokeseen">Github</a>. Statistics were determined from <a href="https://bulbapedia.bulbagarden.net/">Bulbapedia</a> data.</p>
      </div>
    </div>
  </div>
)

/**
 * Base HTML wrapper for the template page.
 */
const wrapPage = (str, { version, commits, hash, homepage, generationTime }) => (
  `<!doctype html>
<html lang="en">
<!--

PokéSeen v${version} (r${commits}, [${hash}]) <${homepage}>
Generated on ${generationTime}.

-->
<head>
  <meta charset="utf-8" />
  <title>Pokémon appearance statistics</title>
  <meta name="viewport" content="width=586,initial-scale=1" />
  <link type="text/css" href="overview.min.css" rel="stylesheet" media="screen" />
  <link type="text/css" href="pokeseen.css" rel="stylesheet" media="screen" />

  <meta property="og:title" content="Pokémon appearance statistics" />
  <meta property="og:url" content="https://msikma.github.io/pokeseen/" />
  <meta property="og:description" content="Statistics about how often each Pokémon appears in the TV show and when we last saw them" />

  <script charset="utf-8" src="pokeseen.js" ></script>
</head>
<body>
${str}
</body>
</html>`
)
